// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVN3iQeTkv1g37WCYKDhrbrf3DbANouog',
    appId: '1:367279364746:web:6fe397613d488b39ceeb73',
    messagingSenderId: '367279364746',
    projectId: 'flowmate-6c80d',
    authDomain: 'flowmate-6c80d.firebaseapp.com',
    storageBucket: 'flowmate-6c80d.firebasestorage.app',
    measurementId: 'G-L32HNWQ4KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhdZ9MMgwwSK1DUaplbCi6Q9Zt6fxrB3E',
    appId: '1:367279364746:android:8086f9e1cec99705ceeb73',
    messagingSenderId: '367279364746',
    projectId: 'flowmate-6c80d',
    storageBucket: 'flowmate-6c80d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsn7Idd8tHXYpClrBDphcnWRCdsIOTbgI',
    appId: '1:367279364746:ios:afeaee3022662a6aceeb73',
    messagingSenderId: '367279364746',
    projectId: 'flowmate-6c80d',
    storageBucket: 'flowmate-6c80d.firebasestorage.app',
    iosClientId: '367279364746-sqne8lkh3642arooh15glptm6rfvm893.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVN3iQeTkv1g37WCYKDhrbrf3DbANouog',
    appId: '1:367279364746:web:fe3a74fd261cfcd1ceeb73',
    messagingSenderId: '367279364746',
    projectId: 'flowmate-6c80d',
    authDomain: 'flowmate-6c80d.firebaseapp.com',
    storageBucket: 'flowmate-6c80d.firebasestorage.app',
    measurementId: 'G-XB35DCMXQW',
  );
}
